name: Building and testing with gradle

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 18 used by gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - uses: gradle/gradle-build-action@v2
      - name: Build with gradle
        run: gradle build -x test
      - name: Test with gradle
        run: gradle test