name: Creates an release branch on release

on:
  release:
    types: [published]

jobs:
  create_brach:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        run: echo "version=$(echo "v1234.34.3" | grep "([0-9]+)" -P -o | head -1)" >> $GITHUB_ENV
      - run: echo "${{env.version}}: