name: Creates an release branch on release

on:
  release:
    types: [published]

jobs:
  create_brach:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        run: echo "version=$(echo "$GITHUB_REF" | grep "([0-9]+)" -P -o | head -1)" >> $GITHUB_ENV
      - name: create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "${{env.version}}"
